---
title: "data.replication.rmd"
author: "Karim Primov"
date: "3/15/2022"
output: html_document
---

Loading libraries
```{r}
library(readr)
library(gbm)
library(tidyverse)
library(ggplot2)
library(tm)
```

Importing data
```{r}
library(readxl)
f <- read_csv("raw.sr.bodysize.sharkabundance.csv")
colnames(f)[1] <- "location"
f2 <- read_excel("raw.sr.bodysize.sharkabundance.xlsx")
f2
colnames(f2)[1] <- "location"
```

Plotting densities of species richness, body size, and shark abundance:

Species Richness
```{r}
#Species Richness
sr.density <- density(f$SR, from = 0)
sr.density.plot <- plot(sr.density)
```

Body Size
```{r}
#Body Size
body.size.density <- density(f$MaxL, from = 0)
body.size.density.plot <- plot(body.size.density)
```

Shark Abundance
```{r}
#Shark Abundance
shark.abund.bysite <- f %>% group_by(f$...1) 
shark.abundance.density <- density(f$TaSharks, from = 0) 
shark.abundance.density.plot <- plot(shark.abundance.density)

```

Boosted Regression Trees

Species Richness
```{r}
#use species richness as the response variable
boost.sp.rich.tree <- gbm(f$SR~f$TaSharks+f$MaxL+f$Depth+f$Chla_median+f$Chla_sd+f$SST_median+f$SST_sd
                          +f$pop_50km+f$pop_500km+f$Dist_nearest_pop+f$Dist_nearest_market+f$HDI+f$Dcoast_km+
                            f$DCoralT_km+f$DistSeamount_km+f$GDP+f$Dist_SMT1500+f$FishingEffort01+f$FishingEffort05, data = f)
summary(boost.sp.rich.tree)

boost.sp.rich.tree.100x <- gbm.more(boost.sp.rich.tree, 100, verbose = FALSE)
summary(boost.sp.rich.tree.100x)

```

Body size
```{r}

```

Shark Abundance
```{r}

```


Shark Abundance Box plots (Figure 1E)
```{r}
f$location <- gsub("[0-9]", "", as.character(f$location)) #removing numbers from location column in df "f"
shark.abund.boxplot <- boxplot(f$TaSharks~f$location)
shark.abund.boxplot
library(tidyverse)
tim <- filter(f, location == "TIM") 
tim
```

```{r}
#
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```